google_analytics: "G-P7YF62DJDB"
url: "https://byte-sized-learning.netlify.app"
baseurl: ""

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"